#!/usr/bin/bash
# ---
# Auto login to vpn using forticlient_cli and secret tool
# ---

vpn_cli='/usr/local/forticlientsslvpn/64bit/forticlientsslvpn_cli'
vpn_server='<vpn-server-address>'
vpn_user="$USER"
vpn_pkcs="<path-to-pkcs-pfx-file>"
vpn_user_pw="$(secret-tool lookup vpnuser mani)"
vpn_pkcs_pw="\\$(secret-tool lookup vpnpkcs mani.pfx)"

printf -v expect_cmds "
set timeout 20
spawn $vpn_cli --server $vpn_server --vpnuser $vpn_user -pkcs12 $vpn_pkcs
expect -ex {Password for VPN:}
send \"$vpn_user_pw\r\"
expect -ex {Password for PKCS#12:}
send \"$vpn_pkcs_pw\r\"
interact
"

expect -c "$expect_cmds"
