#!/bin/zsh
#
# shellcheck shell=bash disable=SC1090

# source shell common settings
if [ -f ~/.config/shellcommon/common/common.sh ]; then
	source ~/.config/shellcommon/common/common.sh
fi

# source zsh options
if [ -f ~/.config/zshrcparts/options/options.zsh ]; then
	source ~/.config/zshrcparts/options/options.zsh
fi

# source zsh keymaps
if [ -f ~/.config/zshrcparts/keymaps/keymaps.zsh ]; then
	source ~/.config/zshrcparts/keymaps/keymaps.zsh
fi

# source zsh configurations
if [ -f ~/.config/zshrcparts/configs/configs.zsh ]; then
	source ~/.config/zshrcparts/configs/configs.zsh
fi

# source zsh completions
if [ -f ~/.config/zshrcparts/completions/completions.zsh ]; then
	source ~/.config/zshrcparts/completions/completions.zsh
fi

# source zsh local settings
if [ -f ~/.config/zshrcparts/local/local.zsh ]; then
	source ~/.config/zshrcparts/local/local.zsh
fi

# source zsh aliases
if [ -f ~/.config/zshrcparts/aliases/aliases.zsh ]; then
	source ~/.config/zshrcparts/aliases/aliases.zsh
fi

# source zsh prompt
if [ -f ~/.config/zshrcparts/prompt/prompt.zsh ]; then
	source ~/.config/zshrcparts/prompt/prompt.zsh
fi

# source zsh plugins
if [ -f ~/.config/zshrcparts/plugins/plugins.zsh ]; then
	source ~/.config/zshrcparts/plugins/plugins.zsh
fi
