#!/bin/bash

# TODO: Add help and an option to force install.

install_home () {
	mapfile -t _pkgs_to_home < <( \
	    find . -maxdepth 1 \
	        \( -name "dot-*rc" -o -name "dot-gitconfig" \
		   -o -name "dot-tmux.conf" \
	        \) -type f -printf "%P\n" | \
	    sort
	)

	for pkg in "${_pkgs_to_home[@]}"
	do
		pkg_dest="$HOME/.${pkg#dot-}"
		if [ ! -f $pkg_dest ]; then
			rel_path=$(realpath --relative-to=$HOME $pkg)
			echo "Installing $pkg to $pkg_dest"
			ln -s "$rel_path" "$pkg_dest"
		fi
	done
}

install_config () {
	mapfile -t _pkgs_to_config < <( \
	    find dot-config/ -maxdepth 1 ! -path dot-config/ -type d \
	        -printf "%p\n" | \
	    sort
	)

	local config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
	for pkg in "${_pkgs_to_config[@]}"
	do
		pkg_dest="$config_home/${pkg#dot-config/}"
		if [ ! -d $pkg_dest ]; then
			rel_path=$(realpath --relative-to=$config_home $pkg)
			echo "Installing $pkg to $pkg_dest"
			ln -s "$rel_path" "$pkg_dest"
		fi
	done
}

install_sshconfig () {
	pkg_ssh_config='dot-ssh/config'
	home_ssh_config="$HOME/.ssh/config"
	if [ ! -f $home_ssh_config ]; then
		rel_path=$(realpath --relative-to=$HOME/.ssh $pkg_ssh_config)
		echo "Installing $pkg_ssh_config to $home_ssh_config"
		ln -s "$rel_path" "$home_ssh_config"
	fi
}

install_home
install_config
install_sshconfig
