#!/bin/bash

# Stop on first error.
set -e

source dot-config/shellcommon/common/common.sh

logfile=$(mktemp -t "dotfiles-install-XXXX")

link_msg () {
	local msg="${GREEN}Linking${RESET} "
	msg+="${BLUE}$1${RESET} "
	msg+="${GREEN}to${RESET} "
	msg+="${CYAN}$2${RESET} "
	msg_fmt "$logfile" "$msg"
}

link () {
	local src="$1"
	local dst="$2"
	ln -s "$src" "$dst"
}

install_home () {
	while IFS= read -r pkg;
	do
		local pkg_dst="${pkg##*/}"
		pkg_dst="$HOME/${pkg_dst/dot-/.}"
		if [ ! -f "$pkg_dst" ]; then
			local pkg_src="${pkg#"$HOME/"}"
			link_msg "${pkg#"$PWD/"}" "${pkg_dst/"$HOME"/'~'}"
			link "$pkg_src" "$pkg_dst"
		fi
	done < <( \
		find "$PWD" -maxdepth 1 \
		\( -name "dot-*rc" -o -name "dot-gitconfig" \
		-o -name "dot-tmux.conf" \
		\) -type f -printf "%p\n" | \
		sort
	)
}

install_local_bin () {
	while IFS= read -r pkg;
	do
		local pkg_dst="${pkg##*/}"
		pkg_dst="$HOME/.local/bin/${pkg_dst/dot-/.}"
		if [ ! -f "$pkg_dst" ]; then
			pkg_src="$(realpath --relative-to="$HOME/.local/bin/" "$pkg")"
			link_msg "${pkg#"$PWD/"}" "${pkg_dst/"$HOME"/'~'}"
			link "$pkg_src" "$pkg_dst"
		fi
	done < <( \
		find "$PWD/dot-local/bin" -maxdepth 1 -type f -printf "%p\n" \
		| sort
	)
}

install_config () {
	while IFS= read -r pkg;
	do
		local pkg_dst="${pkg##*/}"
		pkg_dst="$xdg_config/$pkg_dst"
		if [ ! -d "$pkg_dst" ]; then
			pkg_src="$(realpath --relative-to="$xdg_config" "$pkg")"
			link_msg "${pkg#"$PWD/"}" "${pkg_dst/"$HOME"/'~'}"
			link "$pkg_src" "$pkg_dst"
		fi
	done < <( \
		find "$PWD/dot-config" -maxdepth 1 \
		-not -path "$PWD/dot-config" -type d -printf "%p\n" | \
		sort
	)
}

link_vimrc () {
	local nvim_home="$xdg_config/nvim"
	local nvim_autoload="$nvim_home/autoload"
	local nvim_data="$xdg_data/nvim"
	local vim_home="$HOME/.vim"
	local vim_autoload="$vim_home/autoload"
	local pkg_src pkg_dst

	# link ~/.vimrc to nvim/init.vim
	pkg_dst="$HOME/.vimrc"
	if [ ! -f "$pkg_dst" ]; then
		local nvim_init="$nvim_home/init.vim"
		pkg_src="${nvim_init#"$HOME/"}"
		link_msg "${nvim_init/"$HOME"/'~'}" "${pkg_dst/"$HOME"/'~'}"
		link "$pkg_src" "$pkg_dst"
	fi

	if [ ! -d "$vim_autoload" ]; then
		mkdir -pv "$vim_autoload"
	fi

	# link vim-plug in nvim to vim
	pkg_dst="$vim_autoload/plug.vim"
	if [ ! -f "$pkg_dst" ]; then
		local nvim_plug="$nvim_data/site/autoload/plug.vim"
		pkg_src="${nvim_plug/"$HOME"/../..}"
		link_msg "${nvim_plug/"$HOME"/'~'}" "${pkg_dst/"$HOME"/'~'}"
		link "$pkg_src" "$pkg_dst"
	fi

	# link 'plugged' in nvim to vim
	pkg_dst="$vim_home/plugged"
	if [ ! -d "$pkg_dst" ]; then
		local nvim_plugged="$nvim_data/plugged"
		pkg_src="${nvim_plugged/"$HOME"/..}"
		link_msg "${nvim_plugged/"$HOME"/'~'}" "${pkg_dst/"$HOME"/'~'}"
		link "$pkg_src" "$pkg_dst"
	fi

	# link all files and folders in nvim home to vim home
	for nvim_src in "$nvim_home"/*;
	do
		local pkg_dst="$vim_home/${nvim_src##*/}"
		if [ ! -e "$pkg_dst" ]; then
			pkg_src="${nvim_src/"$HOME"/..}"
			link_msg "${nvim_src/"$HOME"/'~'}" "${pkg_dst/"$HOME"/'~'}"
			link "$pkg_src" "$pkg_dst"
		fi
	done

	# link all files and folders in nvim autoload to vim autoload
	for nvim_src in "$nvim_autoload"/*;
	do
		local pkg_dst="$vim_autoload/${nvim_src##*/}"
		if [ ! -e "$pkg_dst" ]; then
			pkg_src="${nvim_src/"$HOME"/../..}"
			link_msg "${nvim_src/"$HOME"/'~'}" "${pkg_dst/"$HOME"/'~'}"
			link "$pkg_src" "$pkg_dst"
		fi
	done
}

install_sshconfig () {
	pkg="dot-ssh/config"
	pkg_dst="$HOME/.ssh/config"
	if [ ! -f "$pkg_dst" ]; then
		pkg_src="$(realpath --relative-to="$HOME/.ssh" "$pkg")"
		link_msg "$pkg" "${pkg_dst/"$HOME"/'~'}"
		link "$pkg_src" "$pkg_dst"
	fi
}

install_home
install_local_bin
install_config
link_vimrc
install_sshconfig
column -t "$logfile"
rm "$logfile"
