#!/bin/bash

# Stop on first error.
set -e

source dot-config/shellcommon/common/common.sh

logfile=$(mktemp -t "dotfiles-uninstall-XXXX")

unlink_msg () {
	local msg="${RED}Remove${RESET} "
	msg+="${BLUE}$1${RESET} "
	msg_fmt "$logfile" "$msg"
}

unlink () {
	local pkg="$1"
	unlink_msg "${pkg/"$HOME"/'~'}"
	rm -rf "$pkg"
}

uninstall_home () {
	while IFS= read -r pkg;
	do
		unlink "$pkg"
	done < <( \
		find "$HOME" -maxdepth 1 \
		\( -name "\.*rc" -o -name "\.gitconfig" \
		-o -name "\.tmux.conf" \
		\) -type l -printf "%p\n" | \
		sort
	)
}

uninstall_local_bin () {
	while IFS= read -r pkg;
	do
		unlink "$HOME/.local/bin/${pkg##*/}"
	done < <( \
		find "$PWD/dot-local/bin" -maxdepth 1 -type f -printf "%p\n" \
		| sort
	)
}

uninstall_config () {
	while IFS= read -r pkg;
	do
		unlink "$pkg"
	done < <( \
		find "$xdg_config" -maxdepth 1 -type l -printf "%p\n" | \
		sort
	)
}

unlink_vimrc () {
	local vim_home="$HOME/.vim"
	while IFS= read -r pkg;
	do
		unlink "$pkg"
	done < <( \
		find "$vim_home" -type l -printf "%p\n" | \
		sort
	)
}

uninstall_sshconfig () {
	pkg="$HOME/.ssh/config"
	if [ -L "$pkg" ]; then
		unlink "$pkg"
	fi
}

uninstall_home
uninstall_local_bin
uninstall_config
unlink_vimrc
uninstall_sshconfig
column -t "$logfile"
rm "$logfile"
