#!/bin/bash
#
# Root bashrc, contains sym links to logically grouped settings
# NOTE: use docker image to test the scripts

# Do nothing in non-interactive session as invoked by scp using sshd
case $- in
*i*) ;;
*) return ;;
esac

# Control bash history
HISTCONTROL=ignoreboth # ignore duplicatess and commands with lead space
HISTSIZE=1000          # no. of cmds stored in memory in present bash session
HISTFILESIZE=2000      # no. of cmds at startup + no. of cmds at session end
shopt -s histappend    # append to previous history

# Check window size after each command, if necessary, updates LINES & COLUMNS
shopt -s checkwinsize

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        source /etc/bash_completion
    fi
fi

#-- begin logical grouping
# source bash options files
if [ -f ~/.bashrc_parts/options/options.sh ]; then
    . ~/.bashrc_parts/options/options.sh
fi

# source bash keymaps files
if [ -f ~/.bashrc_parts/keymaps/keymaps.sh ]; then
    . ~/.bashrc_parts/keymaps/keymaps.sh
fi

# source bash configs files
if [ -f ~/.bashrc_parts/configs/configs.sh ]; then
    . ~/.bashrc_parts/configs/configs.sh
fi

# source bash completions files
if [ -f ~/.bashrc_parts/completions/completions.sh ]; then
    . ~/.bashrc_parts/completions/completions.sh
fi

# source bash aliases files
if [ -f ~/.bashrc_parts/aliases/aliases.sh ]; then
    . ~/.bashrc_parts/aliases/aliases.sh
fi

# source plugins files
if [ -f ~/.bashrc_parts/plugins/plugins.sh ]; then
    . ~/.bashrc_parts/plugins/plugins.sh
fi
